/// <auto-generated>
/// This file is auto-generated by Ceres.FlowCSharpRuntimeGenerator. 
/// All changes will be discarded.
/// </auto-generated>
using Ceres.Graph.Flow;
using UnityEngine;

namespace Ceres.Generated.Flow
{
    internal static class FlowGeneratedProgramRegistryBootstrap
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void RegisterGeneratedPrograms()
        {
            FlowGeneratedProgramRegistry.Clear();
            FlowGeneratedProgramRegistry.Register("9ba197aa37c12eb4486bf4bdc208a7bd", "B101761BDCB82CF1", "Ceres.Generated.Flow.FlowProgram_FillLight_9ba197aa", graphData => new global::Ceres.Generated.Flow.FlowProgram_FillLight_9ba197aa(graphData));
        }
    }
}
