/// <auto-generated>
/// This file is auto-generated by Ceres.FlowCSharpRuntimeGenerator. 
/// All changes will be discarded.
/// </auto-generated>

using System.Threading;
using Ceres.Graph;
using Ceres.Graph.Flow;
using Ceres.Graph.Flow.Utilities;
using Chris.Resource;
using Chris.Events;
using Cysharp.Threading.Tasks;
using R3;
using R3.Chris;
using UnityEngine;
using UnityEngine.Pool;
using UObject = UnityEngine.Object;

namespace Ceres.Generated.Flow
{
    public sealed class FlowProgram_FillLight_9ba197aa : FlowGeneratedProgram
    {
        private float _local_seed_0;
        private global::UnityEngine.Light _port_77465a7b_847f_42f4_b2c1_49e9d86d5f4d_output;

        public FlowProgram_FillLight_9ba197aa(FlowGraphData graphData) : base(graphData, false)
        {
            _local_seed_0 = FlowGeneratedRuntimeUtility.GetLocalVariableValue<global::Ceres.Graph.SharedFloat, float>(graphData, "seed");
            _port_77465a7b_847f_42f4_b2c1_49e9d86d5f4d_output = FlowGeneratedRuntimeUtility.GetNodePortDefaultValue<global::UnityEngine.Light>(graphData, "77465a7b-847f-42f4-b2c1-49e9d86d5f4d", "output", -1);
        }

        public override bool TryExecuteEvent(global::UnityEngine.Object contextObject, string eventName, global::Chris.Events.EventBase evtBase = null)
        {
            switch (eventName)
            {
                        case "Start":
                        {
                            Execute_Start_3c48df07_ee67_480d_bc01_5e38d2648744(contextObject, evtBase);
                            return true;
                        }
                        case "Update":
                        {
                            Execute_Update_089ecc1c_2914_4e8f_b080_aaae65d6000d(contextObject, evtBase);
                            return true;
                        }
                        default:
                            return false;
                    }
        }

        private void Execute_Start_3c48df07_ee67_480d_bc01_5e38d2648744(global::UnityEngine.Object contextObject, global::Chris.Events.EventBase evtBase)
        {
            try
            {
                PushExecutionContext(contextObject);
                float value_output_0f09c2fc_d7e8_4590_8d42_ef773ebf263e_0 = global::Ceres.Graph.Flow.Utilities.UnityExecutableLibrary.Flow_RandomRange((float)(0f), (float)(6.28318f));
                _local_seed_0 = value_output_0f09c2fc_d7e8_4590_8d42_ef773ebf263e_0;
                _port_77465a7b_847f_42f4_b2c1_49e9d86d5f4d_output = (global::UnityEngine.Light)((global::UnityEngine.Component)(contextObject as global::UnityEngine.Component).GetComponentInChildren<global::UnityEngine.Light>());
            }
            finally
            {
                PopExecutionContext(contextObject);
            }
        }

        private void Execute_Update_089ecc1c_2914_4e8f_b080_aaae65d6000d(global::UnityEngine.Object contextObject, global::Chris.Events.EventBase evtBase)
        {
            try
            {
                PushExecutionContext(contextObject);
                float value_outputValue_24944190_e8fc_4b60_850f_692d1dafbeb6_0 = _local_seed_0;
                _port_77465a7b_847f_42f4_b2c1_49e9d86d5f4d_output.intensity = Mathf.Lerp((float)(10f), (float)(100f), (float)((((float)((((float)(Mathf.Sin((float)((((float)((((float)(Time.time)) * ((float)(2f))))) + ((float)(value_outputValue_24944190_e8fc_4b60_850f_692d1dafbeb6_0))))))) + ((float)(1f))))) * ((float)(0.5f)))));
            }
            finally
            {
                PopExecutionContext(contextObject);
            }
        }

    }
}
